server:
  port: 9092
spring:
  application:
    name: Gestion de Stock
  datasource:
    username: root
    password: Jumpy07A2668
    url: jdbc:mysql://localhost:3306/GestionStk
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      #format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

flickr:
  apiKey: 232e1419f7d13e2129d0cbb96f579f0d
  apiSecret: ef376497ece67811
  appKey: 72157720898351182-f8719838af94436c
  appSecret: e46cdaa9d54bb173

springdoc:
  api-docs:
    path: /api-GestionStock

